name: mp1 autograding
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v2
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v2
      with:
        repository: cs340-illinois/sp23_cs340_.release
        ref: mp1
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp1
        dst_path: mp1
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp1/.github/classroom : mp1/.github/classroom, release/mp1/Makefile : mp1/Makefile, release/mp1/tests : mp1/tests'
    - name: Autograding
      id: autograding
      uses: wadefagen/autograding@v2
      with:
        path: mp1/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
  valgrind:
    name: valgrind
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v2
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v2
      with:
        repository: cs340-illinois/sp23_cs340_.release
        ref: mp1
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp1
        dst_path: mp1
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp1/.github/classroom : mp1/.github/classroom, release/mp1/Makefile : mp1/Makefile, release/mp1/tests : mp1/tests'
    - name: Install valgrind
      run: sudo apt install -y valgrind
    - name: Autograding
      id: autograding
      uses: wadefagen/autograding@v2
      with:
        path: mp1/
        test_suite: valgrind
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
    needs:
    - autograding
