name: mp3 autograding
'on':
  workflow_dispatch: {}
jobs:
  week2:
    name: week2
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp23_cs340_.release
        ref: mp3
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp3
        dst_path: mp3
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests, lib : lib'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp3/.github/classroom : mp3/.github/classroom, release/mp3/Makefile : mp3/Makefile, release/mp3/tests : mp3/tests, release/mp3/lib : mp3/lib'
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp3/
        test_suite: week2
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
    needs:
    - autograding
  autograding:
    name: autograding
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp23_cs340_.release
        ref: mp3
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp3
        dst_path: mp3
        copy: '.github/classroom : .github/classroom, Makefile : Makefile, tests : tests, lib : lib'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp3/.github/classroom : mp3/.github/classroom, release/mp3/Makefile : mp3/Makefile, release/mp3/tests : mp3/tests, release/mp3/lib : mp3/lib'
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp3/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
