name: mp7 autograding
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on:
    - self-hosted
    - linux
    timeout-minutes: 5
    steps:
    - name: Checkout release repository
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: cs340-illinois/sp23_cs340_.release
        ref: mp7
        path: release
    - name: Copy local files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/mp7
        dst_path: mp7
        copy: '.github/classroom : .github/classroom, test_flask.py : test_flask.py, test_vm.py : test_vm.py, test_vm-mappings.json : test_vm-mappings.json, sample : sample'
    - name: Verify student submission
      id: verify-policy
      uses: illinois/verify-policy@v1
      with:
        reference_files: 'release/mp7/.github/classroom : mp7/.github/classroom, release/mp7/test_flask.py : mp7/test_flask.py, release/mp7/test_vm.py : mp7/test_vm.py, release/mp7/test_vm-mappings.json : mp7/test_vm-mappings.json, release/mp7/sample : mp7/sample'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install -r mp7/requirements.txt
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: mp7/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        release_checkout_status: ${{ steps.release-checkout.outcome }}
        local_copy_status: ${{ steps.local-copy.outcome }}
        verify_policy_status: ${{ steps.verify-policy.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
